import computerIcon from "@iconify-icons/clarity/computer-line";
import phoneIcon from "@iconify-icons/clarity/mobile-phone-line";
import gamepadIcon from "@iconify/icons-cil/gamepad";
import cpuIcon from "@iconify-icons/clarity/cpu-line";
import mouseIcon from "@iconify-icons/clarity/mouse-line";
import tvIcon from "@iconify/icons-bi/tv";
import homeIcon from "@iconify-icons/clarity/home-line";
import boltIcon from "@iconify-icons/clarity/bolt-line";

import matebookImg from "@assets/images/matebookd14.png";
import xiaomiImg from "@assets/images/xiaomi.svg";
import redmiImg from "@assets/images/redmi.png";
import huaweiImg from "@assets/images/huawei.svg";

const computers = {
  name: "Komputery i laptopy",
  icon: computerIcon,
  featuredProduct: {
    title: "Huawei Matebook D14",
    attributes: [
      "AMD Ryzen 7 2700u",
      "AMD Radeon Vega 10",
      "Microsoft Windows 10 Home",
    ],
    price: "2720",
    image: matebookImg,
    markImg: huaweiImg,
  },
  subcategories: [
    {
      name: "Laptopy, notebooki, ultrabooki",
      subcategories: [
        "Laptopy 2 w 1",
        'Notebooki / Laptopy 17,3"',
        'Notebooki / Laptopy 17"',
        'Notebooki / Laptopy 16"',
        'Notebooki / Laptopy 15,6"',
        'Notebooki / Laptopy 15,0"',
        'Notebooki / Laptopy 14,1"',
        'Notebooki / Laptopy 14,0"',
        'Notebooki / Laptopy 13,9"',
        'Notebooki / Laptopy 13,3"',
        'Notebooki / Laptopy 11,6"',
      ],
    },
    {
      name: "Laptopy 2 w 1",
      subcategories: null,
    },
    {
      name: "Komputery i serwisy",
      subcategories: ["Desktopy", "All-in-One", "Nettopy/Mini-PC", "Serwery"],
    },
    {
      name: "Komputery HT",
      subcategories: null,
    },
    {
      name: "Programy",
      subcategories: [
        "Systemy operacyjne",
        "Programy biurowe",
        "Programy antywirusowe",
        "Programy graficzne i wideo",
        "Programy użytkowe",
        "Programy serwerowe",
        "Programy edukacyjne",
        "Kontrola rodzicielska",
        "Systemy sprzedaży",
        "Mapy do nawigacji GPS",
      ],
    },
    {
      name: "Torby i etui",
      subcategories: [
        "Torby na laptopy",
        "Plecaki na laptopy",
        "Etui na laptopy",
      ],
    },
    {
      name: "Akcesoria do laptopów",
      subcategories: [
        "Torby na laptopy",
        "Plecaki na laptopy",
        "Etui na laptopy",
        "Podstawki chłodzące",
        "Stacje dokujące do laptopów",
        "Pendrive (pamięci USB)",
        "Pamięci RAM do laptopów",
        "Baterie do laptopów",
        "Zasilacze do laptopów",
        "Rozszerzone gwarancje laptopów",
        "Filtry na laptopy",
        "Zaślepki na kamerę laptopa",
        "Replikatory portów",
        "Linki zabezpieczające",
      ],
    },
    {
      name: "Akcesoria komputerowe",
      subcategories: [
        "Myszki przewodowe",
        "Myszki bezprzewodowe",
        "Klawiatury przewodowe",
        "Klawiatury bezprzewodowe",
        "Zestawy klawiatura i mysz",
        "Kamery internetowe",
        "Pendrive (pamięci USB)",
        "Słuchawki nauszne",
        "Głośniki komputerowe",
        "Mouse bungee",
        "Moduły Bluetooth",
        "Kontrolery",
        "Huby USB",
      ],
    },
  ],
};

const phones = {
  name: "Telefony i smartwatche",
  icon: phoneIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        'Tablety 13"',
        'Tablety 12"',
        'Tablety 11"',
        'Tablety 10"',
        'Tablety 8"',
        'Tablety 7"',
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        "Smartwatche",
        "Smartwatche LTE",
        "Smartwatche dla dzieci",
        "Smartbandy",
        "Zegarki sportowe",
        "Pulsometry",
        "Paski i bransoletki",
        "Ładowarki do smartwatchy",
        "Etui i obudowy na smartwatche",
        "Folie ochronne na smartwatche",
        "Inteligentne wagi",
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        "Pendrive (pamięci USB)",
        "Karty pamięci microSD",
        "Karty pamięci SD",
        "Karty pamięci CF",
        "Karty pamięci CFast",
        "Czytniki kart USB",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        "Etui i obudowy na smartfony",
        "Folie i szkła na smartfony",
        "Karty pamięci microSD (121)",
        "Kijki do selfie",
        "Uchwyty do smartfonów",
        "Stacje dokujące do smartfonów",
        "Moduły do smartfonów",
        "Opaski naramienne",
        "Monitory aktywności",
        "Ładowarki do smartfonów",
        "Baterie do smartfonów",
        "Słuchawki douszne i dokanałowe",
        "Głośniki przenośne",
        "Zestawy głośnomówiące",
        "Zestawy słuchawkowe",
        "Powerbanki",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        "Etui na tablety",
        "Klawiatury do tabletów",
        "Rysiki do tabletów",
        "Uchwyty do tabletów",
        "Folie ochronne na tablety",
        "Karty pamięci microSD",
        "Powerbanki",
        "Ładowarki do tabletów",
      ],
    },
  ],
};

const gaming = {
  name: "Gaming i streaming",
  icon: gamepadIcon,
  featuredProduct: {
    title: "Huawei Matebook D14",
    attributes: [
      "AMD Ryzen 7 2700u",
      "AMD Radeon Vega 10",
      "Microsoft Windows 10 Home",
    ],
    price: "2720",
    image: matebookImg,
    markImg: huaweiImg,
  },
  subcategories: [
    {
      name: "Laptopy, notebooki, ultrabooki",
      subcategories: [
        "Laptopy 2 w 1",
        'Notebooki / Laptopy 17,3"',
        'Notebooki / Laptopy 17"',
        'Notebooki / Laptopy 16"',
        'Notebooki / Laptopy 15,6"',
        'Notebooki / Laptopy 15,0"',
        'Notebooki / Laptopy 14,1"',
        'Notebooki / Laptopy 14,0"',
        'Notebooki / Laptopy 13,9"',
        'Notebooki / Laptopy 13,3"',
        'Notebooki / Laptopy 11,6"',
      ],
    },
    {
      name: "Laptopy 2 w 1",
      subcategories: null,
    },
    {
      name: "Komputery i serwisy",
      subcategories: ["Desktopy", "All-in-One", "Nettopy/Mini-PC", "Serwery"],
    },
    {
      name: "Komputery HT",
      subcategories: null,
    },
    {
      name: "Programy",
      subcategories: [
        "Systemy operacyjne",
        "Programy biurowe",
        "Programy antywirusowe",
        "Programy graficzne i wideo",
        "Programy użytkowe",
        "Programy serwerowe",
        "Programy edukacyjne",
        "Kontrola rodzicielska",
        "Systemy sprzedaży",
        "Mapy do nawigacji GPS",
      ],
    },
    {
      name: "Torby i etui",
      subcategories: [
        "Torby na laptopy",
        "Plecaki na laptopy",
        "Etui na laptopy",
      ],
    },
    {
      name: "Akcesoria do laptopów",
      subcategories: [
        "Torby na laptopy",
        "Plecaki na laptopy",
        "Etui na laptopy",
        "Podstawki chłodzące",
        "Stacje dokujące do laptopów",
        "Pendrive (pamięci USB)",
        "Pamięci RAM do laptopów",
        "Baterie do laptopów",
        "Zasilacze do laptopów",
        "Rozszerzone gwarancje laptopów",
        "Filtry na laptopy",
        "Zaślepki na kamerę laptopa",
        "Replikatory portów",
        "Linki zabezpieczające",
      ],
    },
    {
      name: "Akcesoria komputerowe",
      subcategories: [
        "Myszki przewodowe",
        "Myszki bezprzewodowe",
        "Klawiatury przewodowe",
        "Klawiatury bezprzewodowe",
        "Zestawy klawiatura i mysz",
        "Kamery internetowe",
        "Pendrive (pamięci USB)",
        "Słuchawki nauszne",
        "Głośniki komputerowe",
        "Mouse bungee",
        "Moduły Bluetooth",
        "Kontrolery",
        "Huby USB",
      ],
    },
  ],
};

const pcComponents = {
  name: "Podzespoły komputerowe",
  icon: cpuIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        'Tablety 13"',
        'Tablety 12"',
        'Tablety 11"',
        'Tablety 10"',
        'Tablety 8"',
        'Tablety 7"',
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        "Smartwatche",
        "Smartwatche LTE",
        "Smartwatche dla dzieci",
        "Smartbandy",
        "Zegarki sportowe",
        "Pulsometry",
        "Paski i bransoletki",
        "Ładowarki do smartwatchy",
        "Etui i obudowy na smartwatche",
        "Folie ochronne na smartwatche",
        "Inteligentne wagi",
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        "Pendrive (pamięci USB)",
        "Karty pamięci microSD",
        "Karty pamięci SD",
        "Karty pamięci CF",
        "Karty pamięci CFast",
        "Czytniki kart USB",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        "Etui i obudowy na smartfony",
        "Folie i szkła na smartfony",
        "Karty pamięci microSD (121)",
        "Kijki do selfie",
        "Uchwyty do smartfonów",
        "Stacje dokujące do smartfonów",
        "Moduły do smartfonów",
        "Opaski naramienne",
        "Monitory aktywności",
        "Ładowarki do smartfonów",
        "Baterie do smartfonów",
        "Słuchawki douszne i dokanałowe",
        "Głośniki przenośne",
        "Zestawy głośnomówiące",
        "Zestawy słuchawkowe",
        "Powerbanki",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        "Etui na tablety",
        "Klawiatury do tabletów",
        "Rysiki do tabletów",
        "Uchwyty do tabletów",
        "Folie ochronne na tablety",
        "Karty pamięci microSD",
        "Powerbanki",
        "Ładowarki do tabletów",
      ],
    },
  ],
};

const periferyDevices = {
  name: "Urządzenia peryferyjne",
  icon: mouseIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        'Tablety 13"',
        'Tablety 12"',
        'Tablety 11"',
        'Tablety 10"',
        'Tablety 8"',
        'Tablety 7"',
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        "Smartwatche",
        "Smartwatche LTE",
        "Smartwatche dla dzieci",
        "Smartbandy",
        "Zegarki sportowe",
        "Pulsometry",
        "Paski i bransoletki",
        "Ładowarki do smartwatchy",
        "Etui i obudowy na smartwatche",
        "Folie ochronne na smartwatche",
        "Inteligentne wagi",
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        "Pendrive (pamięci USB)",
        "Karty pamięci microSD",
        "Karty pamięci SD",
        "Karty pamięci CF",
        "Karty pamięci CFast",
        "Czytniki kart USB",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        "Etui i obudowy na smartfony",
        "Folie i szkła na smartfony",
        "Karty pamięci microSD (121)",
        "Kijki do selfie",
        "Uchwyty do smartfonów",
        "Stacje dokujące do smartfonów",
        "Moduły do smartfonów",
        "Opaski naramienne",
        "Monitory aktywności",
        "Ładowarki do smartfonów",
        "Baterie do smartfonów",
        "Słuchawki douszne i dokanałowe",
        "Głośniki przenośne",
        "Zestawy głośnomówiące",
        "Zestawy słuchawkowe",
        "Powerbanki",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        "Etui na tablety",
        "Klawiatury do tabletów",
        "Rysiki do tabletów",
        "Uchwyty do tabletów",
        "Folie ochronne na tablety",
        "Karty pamięci microSD",
        "Powerbanki",
        "Ładowarki do tabletów",
      ],
    },
  ],
};

const tv = {
  name: "TV i audio",
  icon: tvIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        'Tablety 13"',
        'Tablety 12"',
        'Tablety 11"',
        'Tablety 10"',
        'Tablety 8"',
        'Tablety 7"',
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        "Smartwatche",
        "Smartwatche LTE",
        "Smartwatche dla dzieci",
        "Smartbandy",
        "Zegarki sportowe",
        "Pulsometry",
        "Paski i bransoletki",
        "Ładowarki do smartwatchy",
        "Etui i obudowy na smartwatche",
        "Folie ochronne na smartwatche",
        "Inteligentne wagi",
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        "Pendrive (pamięci USB)",
        "Karty pamięci microSD",
        "Karty pamięci SD",
        "Karty pamięci CF",
        "Karty pamięci CFast",
        "Czytniki kart USB",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        "Etui i obudowy na smartfony",
        "Folie i szkła na smartfony",
        "Karty pamięci microSD (121)",
        "Kijki do selfie",
        "Uchwyty do smartfonów",
        "Stacje dokujące do smartfonów",
        "Moduły do smartfonów",
        "Opaski naramienne",
        "Monitory aktywności",
        "Ładowarki do smartfonów",
        "Baterie do smartfonów",
        "Słuchawki douszne i dokanałowe",
        "Głośniki przenośne",
        "Zestawy głośnomówiące",
        "Zestawy słuchawkowe",
        "Powerbanki",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        "Etui na tablety",
        "Klawiatury do tabletów",
        "Rysiki do tabletów",
        "Uchwyty do tabletów",
        "Folie ochronne na tablety",
        "Karty pamięci microSD",
        "Powerbanki",
        "Ładowarki do tabletów",
      ],
    },
  ],
};

const smarthome = {
  name: "Smarthome i lifestyle",
  icon: homeIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        'Tablety 13"',
        'Tablety 12"',
        'Tablety 11"',
        'Tablety 10"',
        'Tablety 8"',
        'Tablety 7"',
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        "Smartwatche",
        "Smartwatche LTE",
        "Smartwatche dla dzieci",
        "Smartbandy",
        "Zegarki sportowe",
        "Pulsometry",
        "Paski i bransoletki",
        "Ładowarki do smartwatchy",
        "Etui i obudowy na smartwatche",
        "Folie ochronne na smartwatche",
        "Inteligentne wagi",
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        "Pendrive (pamięci USB)",
        "Karty pamięci microSD",
        "Karty pamięci SD",
        "Karty pamięci CF",
        "Karty pamięci CFast",
        "Czytniki kart USB",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        "Etui i obudowy na smartfony",
        "Folie i szkła na smartfony",
        "Karty pamięci microSD (121)",
        "Kijki do selfie",
        "Uchwyty do smartfonów",
        "Stacje dokujące do smartfonów",
        "Moduły do smartfonów",
        "Opaski naramienne",
        "Monitory aktywności",
        "Ładowarki do smartfonów",
        "Baterie do smartfonów",
        "Słuchawki douszne i dokanałowe",
        "Głośniki przenośne",
        "Zestawy głośnomówiące",
        "Zestawy słuchawkowe",
        "Powerbanki",
        "Czytniki kart do smartfonów",
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        "Etui na tablety",
        "Klawiatury do tabletów",
        "Rysiki do tabletów",
        "Uchwyty do tabletów",
        "Folie ochronne na tablety",
        "Karty pamięci microSD",
        "Powerbanki",
        "Ładowarki do tabletów",
      ],
    },
  ],
};

const accessories = {
  name: "Akcesoria",
  icon: boltIcon,
  featuredProduct: {
    title: "Huawei Matebook D14",
    attributes: [
      "AMD Ryzen 7 2700u",
      "AMD Radeon Vega 10",
      "Microsoft Windows 10 Home",
    ],
    price: "2720",
    image: matebookImg,
    markImg: huaweiImg,
  },
  subcategories: [
    {
      name: "Laptopy, notebooki, ultrabooki",
      subcategories: [
        "Laptopy 2 w 1",
        'Notebooki / Laptopy 17,3"',
        'Notebooki / Laptopy 17"',
        'Notebooki / Laptopy 16"',
        'Notebooki / Laptopy 15,6"',
        'Notebooki / Laptopy 15,0"',
        'Notebooki / Laptopy 14,1"',
        'Notebooki / Laptopy 14,0"',
        'Notebooki / Laptopy 13,9"',
        'Notebooki / Laptopy 13,3"',
        'Notebooki / Laptopy 11,6"',
      ],
    },
    {
      name: "Laptopy 2 w 1",
      subcategories: null,
    },
    {
      name: "Komputery i serwisy",
      subcategories: ["Desktopy", "All-in-One", "Nettopy/Mini-PC", "Serwery"],
    },
    {
      name: "Komputery HT",
      subcategories: null,
    },
    {
      name: "Programy",
      subcategories: [
        "Systemy operacyjne",
        "Programy biurowe",
        "Programy antywirusowe",
        "Programy graficzne i wideo",
        "Programy użytkowe",
        "Programy serwerowe",
        "Programy edukacyjne",
        "Kontrola rodzicielska",
        "Systemy sprzedaży",
        "Mapy do nawigacji GPS",
      ],
    },
    {
      name: "Torby i etui",
      subcategories: [
        "Torby na laptopy",
        "Plecaki na laptopy",
        "Etui na laptopy",
      ],
    },
    {
      name: "Akcesoria do laptopów",
      subcategories: [
        "Torby na laptopy",
        "Plecaki na laptopy",
        "Etui na laptopy",
        "Podstawki chłodzące",
        "Stacje dokujące do laptopów",
        "Pendrive (pamięci USB)",
        "Pamięci RAM do laptopów",
        "Baterie do laptopów",
        "Zasilacze do laptopów",
        "Rozszerzone gwarancje laptopów",
        "Filtry na laptopy",
        "Zaślepki na kamerę laptopa",
        "Replikatory portów",
        "Linki zabezpieczające",
      ],
    },
    {
      name: "Akcesoria komputerowe",
      subcategories: [
        "Myszki przewodowe",
        "Myszki bezprzewodowe",
        "Klawiatury przewodowe",
        "Klawiatury bezprzewodowe",
        "Zestawy klawiatura i mysz",
        "Kamery internetowe",
        "Pendrive (pamięci USB)",
        "Słuchawki nauszne",
        "Głośniki komputerowe",
        "Mouse bungee",
        "Moduły Bluetooth",
        "Kontrolery",
        "Huby USB",
      ],
    },
  ],
};

export default [
  computers,
  phones,
  gaming,
  pcComponents,
  periferyDevices,
  tv,
  smarthome,
  accessories,
];
