import computerIcon from "@iconify-icons/clarity/computer-line";
import phoneIcon from "@iconify-icons/clarity/mobile-phone-line";
import gamepadIcon from "@iconify/icons-cil/gamepad";
import cpuIcon from "@iconify-icons/clarity/cpu-line";
import mouseIcon from "@iconify-icons/clarity/mouse-line";
import tvIcon from "@iconify/icons-bi/tv";
import homeIcon from "@iconify-icons/clarity/home-line";
import boltIcon from "@iconify-icons/clarity/bolt-line";

import matebookImg from "@assets/images/matebookd14.png";
import xiaomiImg from "@assets/images/xiaomi.svg";
import redmiImg from "@assets/images/redmi.png";
import huaweiImg from "@assets/images/huawei.svg";

const computers = {
  name: "Komputery i laptopy",
  icon: computerIcon,
  featuredProduct: {
    title: "Huawei Matebook D14",
    attributes: [
      "AMD Ryzen 7 2700u",
      "AMD Radeon Vega 10",
      "Microsoft Windows 10 Home",
    ],
    price: "2720",
    image: matebookImg,
    markImg: huaweiImg,
  },
  subcategories: [
    {
      name: "Laptopy, notebooki, ultrabooki",
      subcategories: [
        { name: "Laptopy 2 w 1" },
        { name: 'Notebooki / Laptopy 17,3"' },
        { name: 'Notebooki / Laptopy 17"' },
        { name: 'Notebooki / Laptopy 16"' },
        { name: 'Notebooki / Laptopy 15,6"' },
        { name: 'Notebooki / Laptopy 15,0"' },
        { name: 'Notebooki / Laptopy 14,1"' },
        { name: 'Notebooki / Laptopy 14,0"' },
        { name: 'Notebooki / Laptopy 13,9"' },
        { name: 'Notebooki / Laptopy 13,3"' },
        { name: 'Notebooki / Laptopy 11,6"' },
      ],
    },
    {
      name: "Laptopy 2 w 1",
      subcategories: null,
    },
    {
      name: "Komputery i serwisy",
      subcategories: [
        { name: "Desktopy" },
        { name: "All-in-One" },
        { name: "Nettopy/Mini-PC" },
        { name: "Serwery" },
      ],
    },
    {
      name: "Komputery HT",
      subcategories: null,
    },
    {
      name: "Programy",
      subcategories: [
        { name: "Systemy operacyjne" },
        { name: "Programy biurowe" },
        { name: "Programy antywirusowe" },
        { name: "Programy graficzne i wideo" },
        { name: "Programy użytkowe" },
        { name: "Programy serwerowe" },
        { name: "Programy edukacyjne" },
        { name: "Kontrola rodzicielska" },
        { name: "Systemy sprzedaży" },
        { name: "Mapy do nawigacji GPS" },
      ],
    },
    {
      name: "Torby i etui",
      subcategories: [
        { name: "Torby na laptopy" },
        { name: "Plecaki na laptopy" },
        { name: "Etui na laptopy" },
      ],
    },
    {
      name: "Akcesoria do laptopów",
      subcategories: [
        { name: "Torby na laptopy" },
        { name: "Plecaki na laptopy" },
        { name: "Etui na laptopy" },
        { name: "Podstawki chłodzące" },
        { name: "Stacje dokujące do laptopów" },
        { name: "Pendrive (pamięci USB)" },
        { name: "Pamięci RAM do laptopów" },
        { name: "Baterie do laptopów" },
        { name: "Zasilacze do laptopów" },
        { name: "Rozszerzone gwarancje laptopów" },
        { name: "Filtry na laptopy" },
        { name: "Zaślepki na kamerę laptopa" },
        { name: "Replikatory portów" },
        { name: "Linki zabezpieczające" },
      ],
    },
    {
      name: "Akcesoria komputerowe",
      subcategories: [
        { name: "Myszki przewodowe" },
        { name: "Myszki bezprzewodowe" },
        { name: "Klawiatury przewodowe" },
        { name: "Klawiatury bezprzewodowe" },
        { name: "Zestawy klawiatura i mysz" },
        { name: "Kamery internetowe" },
        { name: "Pendrive (pamięci USB)" },
        { name: "Słuchawki nauszne" },
        { name: "Głośniki komputerowe" },
        { name: "Mouse bungee" },
        { name: "Moduły Bluetooth" },
        { name: "Kontrolery" },
        { name: "Huby USB" },
      ],
    },
  ],
};

const phones = {
  name: "Telefony i smartwatche",
  icon: phoneIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        { name: 'Tablety 13"' },
        { name: 'Tablety 12"' },
        { name: 'Tablety 11"' },
        { name: 'Tablety 10"' },
        { name: 'Tablety 8"' },
        { name: 'Tablety 7"' },
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        { name: "Smartwatche" },
        { name: "Smartwatche LTE" },
        { name: "Smartwatche dla dzieci" },
        { name: "Smartbandy" },
        { name: "Zegarki sportowe" },
        { name: "Pulsometry" },
        { name: "Paski i bransoletki" },
        { name: "Ładowarki do smartwatchy" },
        { name: "Etui i obudowy na smartwatche" },
        { name: "Folie ochronne na smartwatche" },
        { name: "Inteligentne wagi" },
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        { name: "Pendrive (pamięci USB)" },
        { name: "Karty pamięci microSD" },
        { name: "Karty pamięci SD" },
        { name: "Karty pamięci CF" },
        { name: "Karty pamięci CFast" },
        { name: "Czytniki kart USB" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        { name: "Etui i obudowy na smartfony" },
        { name: "Folie i szkła na smartfony" },
        { name: "Karty pamięci microSD (121)" },
        { name: "Kijki do selfie" },
        { name: "Uchwyty do smartfonów" },
        { name: "Stacje dokujące do smartfonów" },
        { name: "Moduły do smartfonów" },
        { name: "Opaski naramienne" },
        { name: "Monitory aktywności" },
        { name: "Ładowarki do smartfonów" },
        { name: "Baterie do smartfonów" },
        { name: "Słuchawki douszne i dokanałowe" },
        { name: "Głośniki przenośne" },
        { name: "Zestawy głośnomówiące" },
        { name: "Zestawy słuchawkowe" },
        { name: "Powerbanki" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        { name: "Etui na tablety" },
        { name: "Klawiatury do tabletów" },
        { name: "Rysiki do tabletów" },
        { name: "Uchwyty do tabletów" },
        { name: "Folie ochronne na tablety" },
        { name: "Karty pamięci microSD" },
        { name: "Powerbanki" },
        { name: "Ładowarki do tabletów" },
      ],
    },
  ],
};

const gaming = {
  name: "Gaming i streaming",
  icon: gamepadIcon,
  featuredProduct: {
    title: "Huawei Matebook D14",
    attributes: [
      "AMD Ryzen 7 2700u",
      "AMD Radeon Vega 10",
      "Microsoft Windows 10 Home",
    ],
    price: "2720",
    image: matebookImg,
    markImg: huaweiImg,
  },
  subcategories: [
    {
      name: "Laptopy, notebooki, ultrabooki",
      subcategories: [
        { name: "Laptopy 2 w 1" },
        { name: 'Notebooki / Laptopy 17,3"' },
        { name: 'Notebooki / Laptopy 17"' },
        { name: 'Notebooki / Laptopy 16"' },
        { name: 'Notebooki / Laptopy 15,6"' },
        { name: 'Notebooki / Laptopy 15,0"' },
        { name: 'Notebooki / Laptopy 14,1"' },
        { name: 'Notebooki / Laptopy 14,0"' },
        { name: 'Notebooki / Laptopy 13,9"' },
        { name: 'Notebooki / Laptopy 13,3"' },
        { name: 'Notebooki / Laptopy 11,6"' },
      ],
    },
    {
      name: "Laptopy 2 w 1",
      subcategories: null,
    },
    {
      name: "Komputery i serwisy",
      subcategories: [
        { name: "Desktopy" },
        { name: "All-in-One" },
        { name: "Nettopy/Mini-PC" },
        { name: "Serwery" },
      ],
    },
    {
      name: "Komputery HT",
      subcategories: null,
    },
    {
      name: "Programy",
      subcategories: [
        { name: "Systemy operacyjne" },
        { name: "Programy biurowe" },
        { name: "Programy antywirusowe" },
        { name: "Programy graficzne i wideo" },
        { name: "Programy użytkowe" },
        { name: "Programy serwerowe" },
        { name: "Programy edukacyjne" },
        { name: "Kontrola rodzicielska" },
        { name: "Systemy sprzedaży" },
        { name: "Mapy do nawigacji GPS" },
      ],
    },
    {
      name: "Torby i etui",
      subcategories: [
        { name: "Torby na laptopy" },
        { name: "Plecaki na laptopy" },
        { name: "Etui na laptopy" },
      ],
    },
    {
      name: "Akcesoria do laptopów",
      subcategories: [
        { name: "Torby na laptopy" },
        { name: "Plecaki na laptopy" },
        { name: "Etui na laptopy" },
        { name: "Podstawki chłodzące" },
        { name: "Stacje dokujące do laptopów" },
        { name: "Pendrive (pamięci USB)" },
        { name: "Pamięci RAM do laptopów" },
        { name: "Baterie do laptopów" },
        { name: "Zasilacze do laptopów" },
        { name: "Rozszerzone gwarancje laptopów" },
        { name: "Filtry na laptopy" },
        { name: "Zaślepki na kamerę laptopa" },
        { name: "Replikatory portów" },
        { name: "Linki zabezpieczające" },
      ],
    },
    {
      name: "Akcesoria komputerowe",
      subcategories: [
        { name: "Myszki przewodowe" },
        { name: "Myszki bezprzewodowe" },
        { name: "Klawiatury przewodowe" },
        { name: "Klawiatury bezprzewodowe" },
        { name: "Zestawy klawiatura i mysz" },
        { name: "Kamery internetowe" },
        { name: "Pendrive (pamięci USB)" },
        { name: "Słuchawki nauszne" },
        { name: "Głośniki komputerowe" },
        { name: "Mouse bungee" },
        { name: "Moduły Bluetooth" },
        { name: "Kontrolery" },
        { name: "Huby USB" },
      ],
    },
  ],
};

const pcComponents = {
  name: "Podzespoły komputerowe",
  icon: cpuIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        { name: 'Tablety 13"' },
        { name: 'Tablety 12"' },
        { name: 'Tablety 11"' },
        { name: 'Tablety 10"' },
        { name: 'Tablety 8"' },
        { name: 'Tablety 7"' },
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        { name: "Smartwatche" },
        { name: "Smartwatche LTE" },
        { name: "Smartwatche dla dzieci" },
        { name: "Smartbandy" },
        { name: "Zegarki sportowe" },
        { name: "Pulsometry" },
        { name: "Paski i bransoletki" },
        { name: "Ładowarki do smartwatchy" },
        { name: "Etui i obudowy na smartwatche" },
        { name: "Folie ochronne na smartwatche" },
        { name: "Inteligentne wagi" },
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        { name: "Pendrive (pamięci USB)" },
        { name: "Karty pamięci microSD" },
        { name: "Karty pamięci SD" },
        { name: "Karty pamięci CF" },
        { name: "Karty pamięci CFast" },
        { name: "Czytniki kart USB" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        { name: "Etui i obudowy na smartfony" },
        { name: "Folie i szkła na smartfony" },
        { name: "Karty pamięci microSD (121)" },
        { name: "Kijki do selfie" },
        { name: "Uchwyty do smartfonów" },
        { name: "Stacje dokujące do smartfonów" },
        { name: "Moduły do smartfonów" },
        { name: "Opaski naramienne" },
        { name: "Monitory aktywności" },
        { name: "Ładowarki do smartfonów" },
        { name: "Baterie do smartfonów" },
        { name: "Słuchawki douszne i dokanałowe" },
        { name: "Głośniki przenośne" },
        { name: "Zestawy głośnomówiące" },
        { name: "Zestawy słuchawkowe" },
        { name: "Powerbanki" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        { name: "Etui na tablety" },
        { name: "Klawiatury do tabletów" },
        { name: "Rysiki do tabletów" },
        { name: "Uchwyty do tabletów" },
        { name: "Folie ochronne na tablety" },
        { name: "Karty pamięci microSD" },
        { name: "Powerbanki" },
        { name: "Ładowarki do tabletów" },
      ],
    },
  ],
};

const periferyDevices = {
  name: "Urządzenia peryferyjne",
  icon: mouseIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        { name: 'Tablety 13"' },
        { name: 'Tablety 12"' },
        { name: 'Tablety 11"' },
        { name: 'Tablety 10"' },
        { name: 'Tablety 8"' },
        { name: 'Tablety 7"' },
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        { name: "Smartwatche" },
        { name: "Smartwatche LTE" },
        { name: "Smartwatche dla dzieci" },
        { name: "Smartbandy" },
        { name: "Zegarki sportowe" },
        { name: "Pulsometry" },
        { name: "Paski i bransoletki" },
        { name: "Ładowarki do smartwatchy" },
        { name: "Etui i obudowy na smartwatche" },
        { name: "Folie ochronne na smartwatche" },
        { name: "Inteligentne wagi" },
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        { name: "Pendrive (pamięci USB)" },
        { name: "Karty pamięci microSD" },
        { name: "Karty pamięci SD" },
        { name: "Karty pamięci CF" },
        { name: "Karty pamięci CFast" },
        { name: "Czytniki kart USB" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        { name: "Etui i obudowy na smartfony" },
        { name: "Folie i szkła na smartfony" },
        { name: "Karty pamięci microSD (121)" },
        { name: "Kijki do selfie" },
        { name: "Uchwyty do smartfonów" },
        { name: "Stacje dokujące do smartfonów" },
        { name: "Moduły do smartfonów" },
        { name: "Opaski naramienne" },
        { name: "Monitory aktywności" },
        { name: "Ładowarki do smartfonów" },
        { name: "Baterie do smartfonów" },
        { name: "Słuchawki douszne i dokanałowe" },
        { name: "Głośniki przenośne" },
        { name: "Zestawy głośnomówiące" },
        { name: "Zestawy słuchawkowe" },
        { name: "Powerbanki" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        { name: "Etui na tablety" },
        { name: "Klawiatury do tabletów" },
        { name: "Rysiki do tabletów" },
        { name: "Uchwyty do tabletów" },
        { name: "Folie ochronne na tablety" },
        { name: "Karty pamięci microSD" },
        { name: "Powerbanki" },
        { name: "Ładowarki do tabletów" },
      ],
    },
  ],
};

const tv = {
  name: "TV i audio",
  icon: tvIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        { name: 'Tablety 13"' },
        { name: 'Tablety 12"' },
        { name: 'Tablety 11"' },
        { name: 'Tablety 10"' },
        { name: 'Tablety 8"' },
        { name: 'Tablety 7"' },
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        { name: "Smartwatche" },
        { name: "Smartwatche LTE" },
        { name: "Smartwatche dla dzieci" },
        { name: "Smartbandy" },
        { name: "Zegarki sportowe" },
        { name: "Pulsometry" },
        { name: "Paski i bransoletki" },
        { name: "Ładowarki do smartwatchy" },
        { name: "Etui i obudowy na smartwatche" },
        { name: "Folie ochronne na smartwatche" },
        { name: "Inteligentne wagi" },
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        { name: "Pendrive (pamięci USB)" },
        { name: "Karty pamięci microSD" },
        { name: "Karty pamięci SD" },
        { name: "Karty pamięci CF" },
        { name: "Karty pamięci CFast" },
        { name: "Czytniki kart USB" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        { name: "Etui i obudowy na smartfony" },
        { name: "Folie i szkła na smartfony" },
        { name: "Karty pamięci microSD (121)" },
        { name: "Kijki do selfie" },
        { name: "Uchwyty do smartfonów" },
        { name: "Stacje dokujące do smartfonów" },
        { name: "Moduły do smartfonów" },
        { name: "Opaski naramienne" },
        { name: "Monitory aktywności" },
        { name: "Ładowarki do smartfonów" },
        { name: "Baterie do smartfonów" },
        { name: "Słuchawki douszne i dokanałowe" },
        { name: "Głośniki przenośne" },
        { name: "Zestawy głośnomówiące" },
        { name: "Zestawy słuchawkowe" },
        { name: "Powerbanki" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        { name: "Etui na tablety" },
        { name: "Klawiatury do tabletów" },
        { name: "Rysiki do tabletów" },
        { name: "Uchwyty do tabletów" },
        { name: "Folie ochronne na tablety" },
        { name: "Karty pamięci microSD" },
        { name: "Powerbanki" },
        { name: "Ładowarki do tabletów" },
      ],
    },
  ],
};

const smarthome = {
  name: "Smarthome i lifestyle",
  icon: homeIcon,
  featuredProduct: {
    title: "Xiaomi Redmi Note 9 Pro 6/128GB Grey",
    attributes: [
      '6.67" ekran IPS',
      "Cztery kamery",
      "16.0 Mpix aparat do selfie",
    ],
    price: "1339",
    discount: "1199",
    image: redmiImg,
    markImg: xiaomiImg,
  },
  subcategories: [
    {
      name: "Smartfony i telefony",
      subcaterogies: null,
    },
    {
      name: "Tablety",
      subcategories: [
        { name: 'Tablety 13"' },
        { name: 'Tablety 12"' },
        { name: 'Tablety 11"' },
        { name: 'Tablety 10"' },
        { name: 'Tablety 8"' },
        { name: 'Tablety 7"' },
      ],
    },
    {
      name: "Inteligentne zegarki",
      subcategories: [
        { name: "Smartwatche" },
        { name: "Smartwatche LTE" },
        { name: "Smartwatche dla dzieci" },
        { name: "Smartbandy" },
        { name: "Zegarki sportowe" },
        { name: "Pulsometry" },
        { name: "Paski i bransoletki" },
        { name: "Ładowarki do smartwatchy" },
        { name: "Etui i obudowy na smartwatche" },
        { name: "Folie ochronne na smartwatche" },
        { name: "Inteligentne wagi" },
      ],
    },
    {
      name: "Czytniki ebook",
      categories: null,
    },
    {
      name: "Pamięci flash",
      categories: [
        { name: "Pendrive (pamięci USB)" },
        { name: "Karty pamięci microSD" },
        { name: "Karty pamięci SD" },
        { name: "Karty pamięci CF" },
        { name: "Karty pamięci CFast" },
        { name: "Czytniki kart USB" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria GSM",
      categories: [
        { name: "Etui i obudowy na smartfony" },
        { name: "Folie i szkła na smartfony" },
        { name: "Karty pamięci microSD (121)" },
        { name: "Kijki do selfie" },
        { name: "Uchwyty do smartfonów" },
        { name: "Stacje dokujące do smartfonów" },
        { name: "Moduły do smartfonów" },
        { name: "Opaski naramienne" },
        { name: "Monitory aktywności" },
        { name: "Ładowarki do smartfonów" },
        { name: "Baterie do smartfonów" },
        { name: "Słuchawki douszne i dokanałowe" },
        { name: "Głośniki przenośne" },
        { name: "Zestawy głośnomówiące" },
        { name: "Zestawy słuchawkowe" },
        { name: "Powerbanki" },
        { name: "Czytniki kart do smartfonów" },
      ],
    },
    {
      name: "Akcesoria do tabletów",
      subcategories: [
        { name: "Etui na tablety" },
        { name: "Klawiatury do tabletów" },
        { name: "Rysiki do tabletów" },
        { name: "Uchwyty do tabletów" },
        { name: "Folie ochronne na tablety" },
        { name: "Karty pamięci microSD" },
        { name: "Powerbanki" },
        { name: "Ładowarki do tabletów" },
      ],
    },
  ],
};

const accessories = {
  name: "Akcesoria",
  icon: boltIcon,
  featuredProduct: {
    title: "Huawei Matebook D14",
    attributes: [
      "AMD Ryzen 7 2700u",
      "AMD Radeon Vega 10",
      "Microsoft Windows 10 Home",
    ],
    price: "2720",
    image: matebookImg,
    markImg: huaweiImg,
  },
  subcategories: [
    {
      name: "Laptopy, notebooki, ultrabooki",
      subcategories: [
        { name: "Laptopy 2 w 1" },
        { name: 'Notebooki / Laptopy 17,3"' },
        { name: 'Notebooki / Laptopy 17"' },
        { name: 'Notebooki / Laptopy 16"' },
        { name: 'Notebooki / Laptopy 15,6"' },
        { name: 'Notebooki / Laptopy 15,0"' },
        { name: 'Notebooki / Laptopy 14,1"' },
        { name: 'Notebooki / Laptopy 14,0"' },
        { name: 'Notebooki / Laptopy 13,9"' },
        { name: 'Notebooki / Laptopy 13,3"' },
        { name: 'Notebooki / Laptopy 11,6"' },
      ],
    },
    {
      name: "Laptopy 2 w 1",
      subcategories: null,
    },
    {
      name: "Komputery i serwisy",
      subcategories: [
        { name: "Desktopy" },
        { name: "All-in-One" },
        { name: "Nettopy/Mini-PC" },
        { name: "Serwery" },
      ],
    },
    {
      name: "Komputery HT",
      subcategories: null,
    },
    {
      name: "Programy",
      subcategories: [
        { name: "Systemy operacyjne" },
        { name: "Programy biurowe" },
        { name: "Programy antywirusowe" },
        { name: "Programy graficzne i wideo" },
        { name: "Programy użytkowe" },
        { name: "Programy serwerowe" },
        { name: "Programy edukacyjne" },
        { name: "Kontrola rodzicielska" },
        { name: "Systemy sprzedaży" },
        { name: "Mapy do nawigacji GPS" },
      ],
    },
    {
      name: "Torby i etui",
      subcategories: [
        { name: "Torby na laptopy" },
        { name: "Plecaki na laptopy" },
        { name: "Etui na laptopy" },
      ],
    },
    {
      name: "Akcesoria do laptopów",
      subcategories: [
        { name: "Torby na laptopy" },
        { name: "Plecaki na laptopy" },
        { name: "Etui na laptopy" },
        { name: "Podstawki chłodzące" },
        { name: "Stacje dokujące do laptopów" },
        { name: "Pendrive (pamięci USB)" },
        { name: "Pamięci RAM do laptopów" },
        { name: "Baterie do laptopów" },
        { name: "Zasilacze do laptopów" },
        { name: "Rozszerzone gwarancje laptopów" },
        { name: "Filtry na laptopy" },
        { name: "Zaślepki na kamerę laptopa" },
        { name: "Replikatory portów" },
        { name: "Linki zabezpieczające" },
      ],
    },
    {
      name: "Akcesoria komputerowe",
      subcategories: [
        { name: "Myszki przewodowe" },
        { name: "Myszki bezprzewodowe" },
        { name: "Klawiatury przewodowe" },
        { name: "Klawiatury bezprzewodowe" },
        { name: "Zestawy klawiatura i mysz" },
        { name: "Kamery internetowe" },
        { name: "Pendrive (pamięci USB)" },
        { name: "Słuchawki nauszne" },
        { name: "Głośniki komputerowe" },
        { name: "Mouse bungee" },
        { name: "Moduły Bluetooth" },
        { name: "Kontrolery" },
        { name: "Huby USB" },
      ],
    },
  ],
};

export default [
  computers,
  phones,
  gaming,
  pcComponents,
  periferyDevices,
  tv,
  smarthome,
  accessories,
];
